<?php

namespace App\Http\Requests\Api;

use Dingo\Api\Http\FormRequest;

class televisionResourcesRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'form' => [
                'required',
            ],
            'category' => [
                'required',
                'in:综合,新闻,财经,体育,娱乐,时尚,科技,其他,生活,文史,军事,旅游,八卦,音乐,电影,少儿,艺术,汽车,健康',
            ],
            'country' => [
                'required',
            ],
        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
